#ifndef _INCLUDED_synapses_1_group_variable_set_conditional_codeobject_1
#define _INCLUDED_synapses_1_group_variable_set_conditional_codeobject_1

#include "objects.h"

void _run_synapses_1_group_variable_set_conditional_codeobject_1();


#endif
