#ifndef _INCLUDED_synapses_group_variable_set_conditional_codeobject
#define _INCLUDED_synapses_group_variable_set_conditional_codeobject

void _run_synapses_group_variable_set_conditional_codeobject();


#endif
