#ifndef _INCLUDED_synapses_1_group_variable_set_conditional_codeobject_1
#define _INCLUDED_synapses_1_group_variable_set_conditional_codeobject_1

void _run_synapses_1_group_variable_set_conditional_codeobject_1();


#endif
